# Generated by Django 3.2.5 on 2021-08-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='node_1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='node_1', to='lw_main.node'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edge',
            name='node_2',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='node_2', to='lw_main.node'),
            preserve_default=False,
        ),
    ]
