# Generated by Django 3.2.5 on 2021-08-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0002_auto_20210803_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='direction',
            field=models.CharField(default='bidirectional', max_length=32),
        ),
    ]
