# Generated by Django 3.2.5 on 2021-08-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0004_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='lw_main.project'),
        ),
        migrations.AlterField(
            model_name='node',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='lw_main.project'),
        ),
    ]
