# Generated by Django 3.2.5 on 2021-08-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0005_auto_20210803_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='node_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_1', to='lw_main.node'),
        ),
        migrations.AlterField(
            model_name='edge',
            name='node_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_2', to='lw_main.node'),
        ),
    ]
