# Generated by Django 3.2.6 on 2021-08-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0007_auto_20210804_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
