# Generated by Django 3.2.6 on 2021-08-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0008_project_is_public'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
