# Generated by Django 3.2.6 on 2021-08-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lw_main', '0009_delete_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
